Repository vanvalenlab/deepcell-tf, pull requests merged in 2021-08, with the labels that each got.

#541 Update TensorFlow to 2.4.3
  .github/workflows/docker-image.yaml
  Dockerfile
  deepcell/_version.py
  requirements.txt
  setup.py
Labels: dependencies, chore

#542 Update TensorFlow to 2.3.4.
  .github/workflows/docker-image.yaml
  Dockerfile
  deepcell/_version.py
  requirements.txt
  setup.py
Labels: dependencies, chore

#543 Bump TensorFlow to 2.5.1
  .github/workflows/docker-image.yaml
  Dockerfile
  requirements.txt
  setup.py
Labels: dependencies, chore

#528 Set `include_top` to `True` by default in `__create_semantic_head`
  deepcell/model_zoo/fpn.py
  notebooks/training/panopticnets/Nuclear Segmentation - DeepWatershed.ipynb
Labels: fix

#546 Bump version to 0.10.0-rc.1
  deepcell/_version.py
Labels: chore

#548 Fix `sed` commands to only replace `tensorflow` not `tensorflow-addons`.
  .github/workflows/pypi.yaml
  deepcell/_version.py
Labels: fix

#545 Support individual parameter passing to Mesmer app
  deepcell/applications/mesmer.py
  deepcell/applications/mesmer_test.py
Labels: enhancement

#549 Remove fully convolutional layers from the GNNTrackingModel.
  deepcell/_version.py
  deepcell/applications/cell_tracking.py
  deepcell/model_zoo/tracking.py
Labels: enhancement
