Repository vanvalenlab/deepcell-tf, pull requests merged in 2022-06, with the labels that each got.

#603 Bump `deepcell-tracking` to 0.6.0
  deepcell/data/tracking.py
  deepcell/utils/tracking_utils.py
  requirements.txt
  setup.py
Labels: dependencies

#602 Create TFRecords for tracking datasets
  deepcell/utils/tfrecord_utils.py
  deepcell/utils/tfrecord_utils_test.py
Labels: enhancement

#606 Fix tracking model bug that pinned n_filters, encoder_dim and embedding_dim to 64
  deepcell/data/tracking.py
  deepcell/model_zoo/tracking.py
Labels: fix

#607 Expose option for fixed crops in the Track data object
  deepcell/data/tracking.py
  requirements.txt
  setup.py
Labels: chore

#605 Bump version to 0.12.1
  README.md
  deepcell/_version.py
Labels: chore

#609 Update mesmer post-processing args
  deepcell/applications/mesmer.py
  notebooks/applications/Mesmer-Application.ipynb
Labels: fix

#610 Add matplotlib to setup.py
  deepcell/_version.py
  setup.py
Labels: fix
