Repository vanvalenlab/deepcell-tf, pull requests merged in 2022-04, with the labels that each got.

#586 Update license badge ("Modified Apache 2.0")
  README.md
Labels: documentation

#590 Pin `jinja2<3.1` to restore functional docs builds
  docs/requirements-docs.txt
Labels: fix, documentation

#589 Update tracking parameters and hashes for new models
  deepcell/applications/cell_tracking.py
Labels: chore, model update
