Repository vanvalenlab/deepcell-tf, pull requests merged in 2023-07, with the labels that each got.

#673 Fix untiling corner-case when no padding in one dimension
  deepcell/applications/application.py
  deepcell/applications/application_test.py
Labels: bug

#674 Bump version for 0.12.6 release
  deepcell/_version.py
  docs/source/conf.py
Labels: chore

#677 STY: ruff str.format -> f-strings.
  deepcell/image_generators/cropping.py
  deepcell/image_generators/fully_convolutional.py
  deepcell/image_generators/sample.py
  deepcell/image_generators/scale.py
  deepcell/image_generators/semantic.py
  deepcell/layers/normalization.py
  deepcell/model_zoo/fpn.py
  deepcell/model_zoo/panopticnet.py
  deepcell/utils/io_utils.py
Labels: chore

#675 Fix scikit-image dependency specification
  deepcell/image_generators/semantic.py
  deepcell/utils/transform_utils.py
  requirements.txt
  setup.py
Labels: bug, dependencies, chore
