Repository vanvalenlab/deepcell-tf, pull requests merged in 2023-01, with the labels that each got.

#633 A collection of minor documentation updates
  docs/requirements-docs.txt
  docs/source/conf.py
  notebooks/training/tracking/Training and Tracking with GNNs.ipynb
Labels: documentation, chore

#637 Update Dockerfile to jupyter lab
  Dockerfile
  requirements.txt
Labels: chore

#634 Fix failures due to invalid numpy scalars.
  .github/workflows/tests.yaml
  deepcell/image_generators/tracking.py
  deepcell/model_zoo/tracking.py
  deepcell/utils/data_utils.py
  deepcell/utils/train_utils.py
  pyproject.toml
  requirements.txt
  setup.py
Labels: chore

#639 Add python3.10 support
  .github/workflows/tests.yaml
  pytest.ini
  requirements-test.txt
  requirements.txt
  setup.py
Labels: chore

#644 Update test to use second num_semantic_classes input.
  deepcell/model_zoo/panopticnet_test.py
Labels: chore

#646 Lint with ruff
  .github/workflows/lint.yaml
  deepcell/callbacks.py
  deepcell/callbacks_test.py
  deepcell/data/tracking.py
  deepcell/image_generators/cropping.py
  deepcell/image_generators/fully_convolutional.py
  deepcell/image_generators/image_generators_test.py
  deepcell/image_generators/semantic.py
  deepcell/image_generators/tracking.py
  deepcell/layers/padding_test.py
  deepcell/layers/temporal_test.py
  deepcell/layers/tensor_product_test.py
  deepcell/layers/upsample_test.py
  deepcell/model_zoo/featurenet.py
  deepcell/model_zoo/fpn.py
  deepcell/model_zoo/panopticnet_test.py
  deepcell/model_zoo/tracking.py
  deepcell/training.py
  deepcell/utils/data_utils_test.py
  deepcell/utils/io_utils_test.py
  deepcell/utils/misc_utils.py
  deepcell/utils/tfrecord_utils.py
  deepcell/utils/tfrecord_utils_test.py
  deepcell/utils/transform_utils.py
  docs/source/conf.py
  pyproject.toml
  requirements-test.txt
  setup.py
Labels: chore

#648 Deprecate export_model_to_tflite
  deepcell/utils/export_utils.py
Labels: chore, deprecation

#649 Deprecate entire `export_utils` module
  deepcell/utils/__init__.py
Labels: chore
