Repository vanvalenlab/deepcell-tf, pull requests merged in 2024-06, with the labels that each got.

#719 General maintenance to make CI happy
  .github/workflows/lint.yaml
  .github/workflows/tests.yaml
  deepcell/datasets/dynamic_nuclear_net.py
  deepcell/datasets/spot_net.py
  deepcell/datasets/tissue_net.py
  docs/requirements-docs.txt
  docs/source/conf.py
  pyproject.toml
Labels: chore

#706 Add SpotNet v1.1
  deepcell/datasets/spot_net.py
  docs/source/datasets/spotnet.py
Labels: datasets

#718 Correct the axis which temporal merges are applied to in tracking model
  deepcell/layers/temporal.py
  deepcell/model_zoo/tracking.py
Labels: fix
